### ISSUE TITLE
Support for LVGL 6.0

### ISSUE THREAD

**Issue by AGlass0fMilk** [rreilink/pylvgl#3]
I'm starting work on the python-based LVGL GUI builder. I think it would be nice to target the upcoming 6.0 release since it supports runtime configuration of certain things like display resolution.

I have been working on updating the python binding generation code to work with LVGL 6.0 (see my fork branch here: https://github.com/AGlass0fMilk/pylvgl/tree/gui-builder-dev)

I am running into a few issues. I have gotten the generated bindings to compile. When I try to import the python library it complains about undefined symbols. So I'm tracing down those one-by-one.

I haven't really worked on Python bindings for C before, let alone the pycparser. I understand how the template is involved.

I'd like to get involved in development of this alongside the GUI builder. @rreilink when you have time can you submit issues that detail things that need to be done? Where is this binding lacking? How could it be better?

**Comment by rreilink** [comment]
@AGlass0fMilk for me, the bindings compile and import properly both under Mac OS and Linux, Using Python 3.6 or 3.7. The current master references lvgl 6.0. 

Can you provide some more details on the errors you are getting?

**Comment by AGlass0fMilk** [comment]
I don't think the current master is pointing to lvgl 6.0 -- it looks to be pointing at lvgl 5.3 still.

I'm targeting the 6.0 feature dev branch - found here: https://github.com/littlevgl/lvgl/tree/dev-6.0

This has a few directory structure changes that require changes to the parser script to work properly.

Also, I'm not sure if it was just my build setup, but I was getting issues with dereferencing user info pointers that are used to store Python object handles. The build was failing because it thought the code was trying to dereference a `void *` when it was actually a `void **`. For example, the following line would cause a build error:

https://github.com/rreilink/pylvgl/blob/2feb64d49ea03f091a8d9680b691256a88c0c3dc/lvglmodule_template.c#L125

To solve this, I had to cast the pointer before dereferencing it:

https://github.com/AGlass0fMilk/pylvgl/blob/gui-builder-dev/lvglmodule_template.c#L125

I fixed all such issues until the build passed. You can look through all my changes thus far here: https://github.com/rreilink/pylvgl/compare/master...AGlass0fMilk:gui-builder-dev

However, now when I import the library I get errors such as this:

```
ImportError: <...>/lv_gui_builder/pylvgl/lvgl.cpython-36m-x86_64-linux-gnu.so: undefined symbol: lv_style_btn_ina
```

Some resources aren't being linked into the library binary. I'm not familiar enough with the binding generator process so I thought I'd ask here first.

**Comment by AGlass0fMilk** [comment]
Ha... that new directory structure really screws everything up.

Had to add the extra `src` subdirectory to `setup.py` when it was looking for source files.

It now builds and imports properly. We should probably update the build scripts to be a little more resilient to directory changes. Maybe use `os.walk` or whatever.

**Comment by embeddedt** [comment]
@AGlass0fMilk 

> We should probably update the build scripts to be a little more resilient to directory changes. Maybe use `os.walk` or whatever.

We aren't planning to change the directory structure in such a major way anytime soon, so it might be more worthwhile to leave it hardcoded for now.

**Comment by rreilink** [comment]
@AGlass0fMilk I added the issues that I think should be addressed on short to medium timeline. If you need anything else (or wat to prioritize), just let me know (e.g. by creating an issue).

I assume that with a new (clean) checkout it all works now (at least it does for me), so I am closing the issue. If you think there is still something to be done, feel free to re-open.

**Comment by AGlass0fMilk** [comment]
@rreilink Oops, I pulled master and synced the lvgl submodule and it does seem that master is targeting lvgl6.0. My mistake.

At least I learned a bit about how the python code is generated. This should help with the lv_gui_builder development!
